sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6.9.1
before_script:
  - npm prune
after_success:
  - npm run catl
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
