// flow-typed signature: dd50a91571fd26ede2c0c1e3ca303aef
// flow-typed version: <<STUB>>/redux-ship_v0.1.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-ship'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-ship' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-ship/dist/main/index' {
  declare module.exports: any;
}

declare module 'redux-ship/dist/main/map' {
  declare module.exports: any;
}

declare module 'redux-ship/dist/main/run' {
  declare module.exports: any;
}

declare module 'redux-ship/dist/main/ship' {
  declare module.exports: any;
}

declare module 'redux-ship/dist/main/simulate' {
  declare module.exports: any;
}

declare module 'redux-ship/dist/main/snap' {
  declare module.exports: any;
}

declare module 'redux-ship/dist/module/index' {
  declare module.exports: any;
}

declare module 'redux-ship/dist/module/map' {
  declare module.exports: any;
}

declare module 'redux-ship/dist/module/run' {
  declare module.exports: any;
}

declare module 'redux-ship/dist/module/ship' {
  declare module.exports: any;
}

declare module 'redux-ship/dist/module/simulate' {
  declare module.exports: any;
}

declare module 'redux-ship/dist/module/snap' {
  declare module.exports: any;
}

declare module 'redux-ship/src/index' {
  declare module.exports: any;
}

declare module 'redux-ship/src/map' {
  declare module.exports: any;
}

declare module 'redux-ship/src/run' {
  declare module.exports: any;
}

declare module 'redux-ship/src/ship' {
  declare module.exports: any;
}

declare module 'redux-ship/src/simulate' {
  declare module.exports: any;
}

declare module 'redux-ship/src/snap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-ship/dist/main/index.js' {
  declare module.exports: $Exports<'redux-ship/dist/main/index'>;
}
declare module 'redux-ship/dist/main/map.js' {
  declare module.exports: $Exports<'redux-ship/dist/main/map'>;
}
declare module 'redux-ship/dist/main/run.js' {
  declare module.exports: $Exports<'redux-ship/dist/main/run'>;
}
declare module 'redux-ship/dist/main/ship.js' {
  declare module.exports: $Exports<'redux-ship/dist/main/ship'>;
}
declare module 'redux-ship/dist/main/simulate.js' {
  declare module.exports: $Exports<'redux-ship/dist/main/simulate'>;
}
declare module 'redux-ship/dist/main/snap.js' {
  declare module.exports: $Exports<'redux-ship/dist/main/snap'>;
}
declare module 'redux-ship/dist/module/index.js' {
  declare module.exports: $Exports<'redux-ship/dist/module/index'>;
}
declare module 'redux-ship/dist/module/map.js' {
  declare module.exports: $Exports<'redux-ship/dist/module/map'>;
}
declare module 'redux-ship/dist/module/run.js' {
  declare module.exports: $Exports<'redux-ship/dist/module/run'>;
}
declare module 'redux-ship/dist/module/ship.js' {
  declare module.exports: $Exports<'redux-ship/dist/module/ship'>;
}
declare module 'redux-ship/dist/module/simulate.js' {
  declare module.exports: $Exports<'redux-ship/dist/module/simulate'>;
}
declare module 'redux-ship/dist/module/snap.js' {
  declare module.exports: $Exports<'redux-ship/dist/module/snap'>;
}
declare module 'redux-ship/src/index.js' {
  declare module.exports: $Exports<'redux-ship/src/index'>;
}
declare module 'redux-ship/src/map.js' {
  declare module.exports: $Exports<'redux-ship/src/map'>;
}
declare module 'redux-ship/src/run.js' {
  declare module.exports: $Exports<'redux-ship/src/run'>;
}
declare module 'redux-ship/src/ship.js' {
  declare module.exports: $Exports<'redux-ship/src/ship'>;
}
declare module 'redux-ship/src/simulate.js' {
  declare module.exports: $Exports<'redux-ship/src/simulate'>;
}
declare module 'redux-ship/src/snap.js' {
  declare module.exports: $Exports<'redux-ship/src/snap'>;
}
